name: On Push

on:
  push:
    branches:
      - main
      - release/*
    paths-ignore:
      - 'readme.md'
      - 'CHANGELOG.md'
      - 'docs/**'

env:
  AZURE_ARTIFACTS_FEED_URL: https://pkgs.dev.azure.com/ngdenterprise/Build/_packaging/public/nuget/v3/index.json
  DOTNET_VERSION: '6.0.x'

jobs:
  pack:
    uses: ./.github/workflows/pack.yml
  publish:
    needs: pack
    runs-on: ubuntu-latest
    steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        source-url: ${{ env.AZURE_ARTIFACTS_FEED_URL }}
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.AZURE_ARTIFACTS_PAT }} 
    - name: Download Shell
      uses: actions/download-artifact@v3
      with:
        name: shell
        path: ./out
    - name: Download WorkNet
      uses: actions/download-artifact@v3
      with:
        name: worknet
        path: ./out
    - name: Publish to Azure Artifacts
      run: dotnet nuget push --api-key AzureArtifacts ./out/*.nupkg