name: Release

on:
  workflow_dispatch:

jobs:
  pack:
    uses: ./.github/workflows/pack.yml
  publish:
    # if: startsWith(github.ref, 'refs/heads/release/')
    # While in preview, release from main branch
    if: github.ref == 'refs/heads/main'
    needs: pack
    runs-on: ubuntu-latest
    steps:
    - name: Download Shell
      uses: actions/download-artifact@v3
      with:
        name: shell
        path: ./out
    - name: Download WorkNet
      uses: actions/download-artifact@v3
      with:
        name: worknet
        path: ./out
    - name: Create Release
      uses: marvinpinto/action-automatic-releases@v1.2.1
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: ${{ needs.pack.outputs.PrereleaseVersion != '' }}
        title: Release ${{ needs.pack.outputs.NuGetPackageVersion }}
        automatic_release_tag: ${{ needs.pack.outputs.NuGetPackageVersion }}
        files: ./out/*
    - name: Push to Nuget.org
      run: dotnet nuget push ./out/*.nupkg --api-key ${{ secrets.NUGET_ORG_TOKEN }} --source https://api.nuget.org/v3/index.json
